### PR TITLE
Revert "use github style uri when using git protocol."

### PR DESCRIPTION
**Pull request by KamranMackey**
Reverts VundleVim/Vundle.vim#616

### CODE REVIEW

**Comment by KamranMackey** [comment]
@gmarik reverted #616, can this be merged?

**Comment by gmarik** [comment]
@KamranMackey let's do hard reset instead. to cfd3b2d38

**Comment by KamranMackey** [comment]
@gmarik you just removed all of the permissions from everyone when doing that hard reset. It no longer says that I'm a collaborator.

**Comment by gmarik** [comment]
@KamranMackey not everyone. Mindless PR merging doesn't help anyone especially if someone else has to fix it later. But thanks for trying!

**Comment by KamranMackey** [comment]
@gmarik please give me back my permissions. I'm sorry for the mindless PR merging.

**Pull request closed without merging**
