### PR TITLE
A change corresponding to f4cea90

### PR DESCRIPTION
**Pull request by VincentTam**
A traditional Chinese version of the updated `README_ZH_CN.md`.

### CODE REVIEW

**Comment by ryanoasis** [comment]
Is this clearer/correct phrasing ? Can someone else verify? :smile:

**Comment by VincentTam** [comment]
The missing word '件' in traditional and simplified Chinese is the *same*.  This can be easily checked using Google Translate.  VundleVim/Vundle.vim#746 has been approved.

**Comment by ryanoasis** [comment]
I did use google translate but didn't help me as it seemed to change the meaning in English.

Does adding this word makes the meaning clearer? If yes I will merge it

**Comment by ryanoasis** [comment]
Does adding this word makes the meaning clearer?

**Comment by VincentTam** [comment]
The purpose of this pull request is the same as f4cea90 : to fix a typo.

**Comment by ryanoasis** [comment]
I will take your word for this :smile: 

Thanks

**Pull request merged**
