### PR TITLE
Update example in readme

### PR DESCRIPTION
**Pull request by wsdjeg**
Reopen https://github.com/VundleVim/Vundle.vim/pull/691

### CODE REVIEW

**Comment by ryanoasis** [comment]
Updated description and alternate name is nice but whats with the repo name change (ascenator)? It was an example faux user before?

**Comment by wsdjeg** [comment]
@ryanoasis because there no username just like `user` ,it just an unexist example

**Comment by ryanoasis** [comment]
Sorry.
Why was the "user' part changed to "ascenator"?

**Comment by wsdjeg** [comment]
because `user` is a nonexistent username,some people who copy this example into ~/.vimrc, when he run PluginInstall, he will get error

**Comment by ryanoasis** [comment]
I see thanks.

However why one of the forks (https://github.com/ascenator/L9) and not https://github.com/vim-scripts/L9 ?

And actually, why not just comment the examples (or at least this one) out by default?

**Comment by wsdjeg** [comment]
> just comment the examples (or at least this one)

nice ,maybe it will be better, but I want the use know ,how `name` option works,he will see a NewL9 directory in ~/.vim/bundle,if we comment it out, it will not work

**Comment by ryanoasis** [comment]
I see, well that makes sense. This is an example after all so it is up to the user to modify it to work for them. That is a good point and this is how I believe it was meant to be anyway:
> Remove plugins you don't need, they are for illustration purposes.

So... basically I think this change looks good and I will merge it in :+1:

**Comment by wsdjeg** [comment]
thanks a lot

**Comment by nfischer** [comment]
:+1:

**Pull request merged**
