### PR TITLE
Git plugin is now hosted on GitHub

### PR DESCRIPTION
**Pull request by lslxdx**
Git plugin is now hosted on GitHub, so I updated the README.md file.

### CODE REVIEW

**Comment by ryanoasis** [comment]
I believe the intention here was to give an example of how to include a plugin not hosted on GitHub.

You are right the command-t is on GitHub but the point was to show how to include a plugin from elsewhere. Therefore there is not a mistake here.

I know your intention but don't think the PR makes sense as is, sorry :blush: 

Of course if anyone else has ideas or opinions feel free to give.

**Comment by nfischer** [comment]
As long as the old link works, I guess we can keep it.

But do many people still install plugins off vimscripts.org? I feel like most people pull straight from github these days.

**Comment by ryanoasis** [comment]
> But do many people still install plugins off vimscripts.org? I feel like most people pull straight from github these days.

Yeah true, no I don't think most people use vimscripts.org these days and instead use GitHub.

--

I think the reason behind the comment and non-GitHub hosted plugin is to show _how_ to do it.

I went back with git blame to get some context...

This seems to be the clear intention: https://github.com/VundleVim/Vundle.vim/commit/286abd12f26d108fd76e9ea626ff4c0bcdcd1b06

So as far as I can tell this is supposed to be a "non GitHub example"

**Comment by nfischer** [comment]
I agree, you're right. I was just pointing out that, since this is probably a not-so-commonly used feature, we might be better served by refactoring the docs, and putting semi-confusing things like the vimscripts.org stuff on a different page.

I personally think the README should be for just super-basic starting out. I vaguely recall seeing a few issues where people post their vimrcs containing the examples from the README copy-pasted, which links to plugins they probably aren't using.

**Comment by ryanoasis** [comment]
@nfischer Sorry, I see what you mean now.

Yeah maybe the default example config in the readme should be shortened and there could be a separate link to (maybe even wiki) a more complete and verbose config that shows all the examples.

**Comment by nfischer** [comment]
> Yeah maybe the default example config in the readme should be shortened and there could be a separate link to (maybe even wiki) a more complete and verbose config that shows all the examples.

+1 for the wiki. I'm becoming more of a fan of putting docs there.

**Comment by lslxdx** [comment]
I make the change simply based on the fact below:

During my `PluginInstall`, the process just stuck at this line `Plugin 'git://git.wincent.com/command-t.git'`. 

Then I tried `git clone git://git.wincent.com/command-t.git` and found the speed was less than 5KB/S, while the speed was more than 200KB/S when I did `git clone git@github.com:wincent/command-t.git`.

**Comment by nfischer** [comment]
@lslxdx I think the point is not to give instructions for that specific plugin (I agree, cloning from github is my preferred source), but to show people how to install some arbitrary plugin from a non-github source (and use that as a specific example).

I think this feature (while still a cool one) is just too confusing. I think the demo should provide instructions on installing from github only, and then have a separate page for installing from vimscripts.org and from local git repos. Vundle's philosophy is KISS, and this seems like the simplest thing to me.

Either way, I vote to close this PR, and I'll probably open a new one to make the README more like what I suggested.

**Comment by lslxdx** [comment]
@nfischer You're right and I agree to close this PR.

**Pull request closed without merging**
