### PR TITLE
Add 'vundlelog' filetype + settings/highlighting

### PR DESCRIPTION
**Pull request by chiphogg**
As requested in #623, I've added some basic syntax highlighting and settings to the syntax file.  I hope this will make it a lot easier for people to see what has changed in their plugins since the previous update.

### CODE REVIEW

**Comment by chiphogg** [comment]
Friendly ping. :)

When's a good time for me to follow up on this?

**Comment by chiphogg** [comment]
I had tweaked the syntax file, but forgotten to test whether `:VundleUpdate` actually _used_ that syntax file!  I found that I had to `:setfiletype vundlelog` manually in the update file.  The root cause was that I stuck that command in the wrong function (`s:view_log` instead of `s:view_changelog`).  I've fixed it in the latest commit.

So as far as I can see, this is ready for review.

By the way, here's a tip I figured out to help test this change, even when all the plugins are up-to-date (so `:VundleUpdate` would do nothing).  I went into a few directories in `~/.vim/bundle/` and manually did `git reset --hard HEAD~5`.  This lets me test many times in quick succession.

**Comment by chiphogg** [comment]
This latest update fixes highlighting for the usernames.  Here's an example input which didn't work with the old regex, but now does work:

```
Updated Plugin: python-mode
Compare at: https://github.com/klen/python-mode/compare/9c8468e83232c3e4...755e99f16501832b
  *   Merge pull request #569 from korzeniewskipl/develop   Kirill Klenov, 6 days ago
  |\
  | * Add wdb to debugger list in breakpoint cmd.   Paweł Korzeniewski, 3 months ago
  *   Merge pull request #572 from GuidoBR/patch-1   Kirill Klenov, 6 days ago
  |\
  | * Documentation is on :help pymode   Guido Percú, 9 weeks ago
  *   Merge pull request #574 from ypid/fixed-disable-trim_whitespaces   Kirill Klenov, 6 days ago
  |\
  | * g:pymode_trim_whitespaces = 0 was ignored.   Robin Schneider, 8 weeks ago
  *   Merge pull request #566 from natezhang93/develop   Kirill Klenov, 6 days ago
  |\
  | * Add Python documentation vertical display option   Nate Zhang, 4 months ago
  *   Merge pull request #562 from wilywampa/hicomments   Kirill Klenov, 6 days ago
  |\
  | * Highlight comments inside class/function arg lists   Jacob Niehus, 4 months ago
  *   Merge pull request #549 from JohnVillalovos/develop   Kirill Klenov, 6 days ago
  |\
  | * Use 'https:' instead of 'git:' in documentation   John L. Villalovos, 5 months ago
  *   Merge pull request #542 from dsem/patch-1   Kirill Klenov, 6 days ago
  |\
  | * fix placement of pymode_options help description   Dylan Semler, 6 months ago
  * Update authors   Kirill Klenov, 6 days ago
  *   Merge pull request #534 from Ram-Z/singleline-def   Kirill Klenov, 6 days ago
  |\
  | * Don't fold single line def   Samir Benmendil, 6 months ago
  *   Merge pull request #533 from Ram-Z/fold-docs   Kirill Klenov, 6 days ago
  |\
  | * Don't skip a line when the first docstring contains text   Samir Benmendil, 6 months ago
  *   merge   Kirill Klenov, 6 days ago
  |\
  | * rope: correct refactoring function calls   Dimitrios Semitsoglou-Tsiapos, 7 months ago
  * Update Rope   Kirill Klenov, 6 days ago
  * Merge branch 'develop' of https://github.com/TFenby/python-mode into TFenby-develop   Kirill Klenov, 6 days ago
  * Update AUTHORS   Tyler Fenby, 8 months ago
  * Upgrade included rope libs to latest releases   Tyler Fenby, 8 months ago
```

Names such as `Guido Percú` failed because `\w` does not match the `ú`.

I have kept my commits in a squashed state at every stage, as per the contributing guidelines.  I believe this PR is ready for review.

**Comment by chiphogg** [comment]
Friendly ping.  I've been using this for weeks without issue now; I think it's ready for review.

**Comment by chiphogg** [comment]
Friendly ping.  After a further two weeks of usage, I still find no issues (and it greatly improves the experience of checking to see what's changed).  I think this is ready for review.

**Comment by ryanoasis** [comment]
I can try to take a look but unfortunately I think most PRs are going to be blocked until #619 can be dealt :worried:

**Comment by chiphogg** [comment]
Thanks for offering.

Are the tests coming soon?  I haven't seen anything substantial on that thread for a few months.  Also, this PR is mostly orthogonal to testing; it only affects the update log.

**Comment by gmarik** [comment]
@chiphogg did quick test and it works well, except that PR needs to be rebased. 
@ryanoasis should be pretty safe to merge as it boils down to single line change.

**Comment by chiphogg** [comment]
Thanks for reviewing!  I've rebased now, and it should be good to go.

**Comment by gmarik** [comment]
@chiphogg thank you! 
@ryanoasis any thoughts? Should be safe to merge, shouldn't it?

**Comment by ryanoasis** [comment]
@gmarik sounds fairly safe yes. If someone can review and merge that's cool else I can try to look at it this weekend :smile:

**Comment by gmarik** [comment]
@ryanoasis feel free to merge it once confirmed! Thanks!

**Comment by ryanoasis** [comment]
This weekend turned out to be pretty busy for me so I wasn't able to get around to this. If someone else can that is great else I will try sometime this week. Cheers!

**Comment by gmarik** [comment]
@ryanoasis @chiphogg ok, i'm gonna test it today…

**Comment by ryanoasis** [comment]
@gmarik :+1: thanks. Sorry I couldn't get around to it.. just had too many other things going on. I will try to contribute on testing perhaps another PR :disappointed:

**Comment by gmarik** [comment]
@ryanoasis hey, no problem!  :)

**Comment by ryanoasis** [comment]
:sweat_smile:

**Comment by gmarik** [comment]
@chiphogg thank you!

**Comment by chiphogg** [comment]
Glad to help.  Thanks for merging :)

**Pull request merged**
