### PR TITLE
gmarik → VundleVim in README.md

### PR DESCRIPTION
**Pull request by julienw**

### CODE REVIEW

**Comment by silfverstrom** [comment]
+1 - only readme changes. 
@ryanoasis

**Comment by julienw** [comment]
I actually noticed https://github.com/VundleVim/Vundle.vim/pull/628 had the same changes already !

**Comment by ryanoasis** [comment]
Oh yep I think #628 should go first

**Comment by silfverstrom** [comment]
#628 resolves this issue as well so i'll close this PR.

**Pull request closed without merging**
