### PR TITLE
Fix misspellings in README_ZH_CN.md

### PR DESCRIPTION
**Pull request by xTire**

### CODE REVIEW

**Comment by ryanoasis** [comment]
Hmm good catch?

I believe you but wondering how best to verify these types of issues

**Comment by xTire** [comment]
Do you mean to verify Chinese language?

**Comment by xTire** [comment]
Because I am a Chinese and I am using Vundle now. I hope more and more people like it without bad translation.
It's just a very simple issue. I believe that my Chinese language skill is hundred thousand times better than my pool English.

**Comment by ryanoasis** [comment]
@xTire Thanks sounds good to me!

**Comment by wsdjeg** [comment]
@xTire Thanks for your PR, LGTM

**Pull request merged**
