### PR TITLE
i have added an readme_zh_cn.md in to this repo!

### PR DESCRIPTION
**Pull request by wsdjeg**
due to the different culture ,i just can keep same article structure

### CODE REVIEW

**Comment by ryanoasis** [comment]
@wsdjeg While I cannot verify anything with this.. the idea is awesome! :+1: :smile:

**Comment by gmarik** [comment]
@ryanoasis @wsdjeg +1! Good stuff!

**Comment by wsdjeg** [comment]
I will finish the todo list tonight,after that i think the Pr could be merged

**Comment by wsdjeg** [comment]
hi @gmarik  i have finished the translation of readme, i am just thinking,if it is necessary for the translation of doc.maybe there is no need,people just need to now how to getting start!

**Comment by wsdjeg** [comment]
any other need i to do?

**Comment by gmarik** [comment]
@wsdjeg thank you! Would you like some other Chinese speaker to review your PR just to double check…?

Other than that: +1 to this.

**Comment by wsdjeg** [comment]
i think there is no need ,i have checked it over and over again

**Comment by nfischer** [comment]
I used Google translate on the new README.md. It looks good to me. Google translate obviously isn't perfect, but it reverse-translates it back to something that's pretty close to the original file. My guess is that the translation by @wsdjeg is more than good enough.

And if there are significant issues, they could always be fixed by a later PR.

**Comment by gmarik** [comment]
@nfischer good point.

**Comment by VincentTam** [comment]
@nfischer As a Hong Kong people whose native language is Chinese, I find that the Chinese translation is excellent, so your guess is right.

However, in Taiwan, Hong Kong, Macao and many overseas Chinese communities, we learn the traditional Chinese characters which are used for over a thousand years, instead of the simplified Chinese characters in `README_ZH_CN.md`.  Therefore, it will be more convenient for us to have a traditional Chinese version of the `README`, which I submitted in #696.

The conversion of simplified Chinese characters to the traditional ones can be done by computer, but the output needs to be proofread because this is not a one-to-one correspondance.

**Pull request merged**
