### PR TITLE
Use github markdown checkmarks

### PR DESCRIPTION
**Pull request by calebeby**

### CODE REVIEW

**Comment by calebeby** [comment]
Anyone?

**Comment by ryanoasis** [comment]
IMHO this looks cleaner and easier to read, so unless anyone has a major disagreement I am included to merge..

Please squash your commits though

**Comment by calebeby** [comment]
I'm having trouble finding out how to do that... Is there a `Merge and Squash` button on your end, since you have write access?

https://help.github.com/articles/about-pull-request-merges/#squash-and-merge-your-pull-request-commits

**Comment by ryanoasis** [comment]
@calebeby Hey yes actually there is now! My bad.. I forgot about that feature (don't use it much personally... yet). Thanks!

**Comment by calebeby** [comment]
How would I squash commits from the command line, if I had to?

**Pull request merged**
